version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongo:27017/employee-app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"  # Changed from 27017 to 27018
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=employee-app

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Changed from 6379 to 6380
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
